### ISSUE TITLE
Does not show on macOS 10.11.6 and VSC 1.45.1

### ISSUE THREAD

**Issue by schroef** [EugeneDae/vscode-mac-color-picker#1]
I tried it latest build and it doesn't show on OSX 10.11.6 using VSC  1.45.1
I don't seem to see an error in the dev log. Nothing that pops out to me.

**Comment by EugeneDae** [comment]
Thanks for taking time to report. I wonder if its node-applescript not working on older systems. Would you mind installing [another extension](https://github.com/EugeneDae/vscode-refresh-browser) that I wrote (it also uses AppleScript) and see if it works for you?
